//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradosToolkit {
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PluginResources {

        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        internal PluginResources() {
        }

        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TradosToolkit.PluginResources", typeof(PluginResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string Plugin_Name {
            get {
                return ResourceManager.GetString("Plugin_Name", resourceCulture);
            }
        }

        public static string Ribbon_Group_Name {
            get {
                return ResourceManager.GetString("Ribbon_Group_Name", resourceCulture);
            }
        }

        public static string Ribbon_Group_Description {
            get {
                return ResourceManager.GetString("Ribbon_Group_Description", resourceCulture);
            }
        }

        public static string Toolkit_Provider_Factory_Name {
            get {
                return ResourceManager.GetString("Toolkit_Provider_Factory_Name", resourceCulture);
            }
        }

        public static string Toolkit_Provider_Factory_Description {
            get {
                return ResourceManager.GetString("Toolkit_Provider_Factory_Description", resourceCulture);
            }
        }

        public static string Toolkit_Provider_WinFormsUI_Name {
            get {
                return ResourceManager.GetString("Toolkit_Provider_WinFormsUI_Name", resourceCulture);
            }
        }

        public static string Toolkit_Provider_WinFormsUI_Description {
            get {
                return ResourceManager.GetString("Toolkit_Provider_WinFormsUI_Description", resourceCulture);
            }
        }

        public static string Qa_Task_Name {
            get {
                return ResourceManager.GetString("Qa_Task_Name", resourceCulture);
            }
        }

        public static string Qa_Task_Description {
            get {
                return ResourceManager.GetString("Qa_Task_Description", resourceCulture);
            }
        }
    }
}
